### ISSUE TITLE
必要の無いグラフを消す

### ISSUE THREAD

**Issue by halsk** [codeforjapan/kobe-stopcovid19#1]
## 改善詳細 / Details of Improvement
- 都営地下鉄の利用者数の推移、都庁来庁者数の推移、新宿・千代田区の人口は削除
- それ以外は、

検査陽性者の状況 | △ | 一番左端に検査実施人数を記載
-- | -- | --
検査実施状況 | × |  
陽性患者の属性 | ◯ |  
陽性患者数 | ◯ |  
検査実施人数 | △ | 「市内でのPCR検査件数及びその内訳」と名称変更   検査実施総数の内訳として、   陰性と陽性に色分け（市ホームページグラフ（下記イメージ参照）
検査実施件数 | × |  
新型コロナコールセンター相談件数 | △ | 「新型コロナ健康相談窓口   相談件数」に名称変更
新型コロナ受診相談窓口相談件数 | △ | 「帰国者・接触者相談センター   相談件数」に名称変更
追加   保健所・保健センターでの一般相談件数 | 追加 |  

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by y-chan** [comment]
#5 のデータの差し替えと一緒にやろうと思います。

**Comment by halsk** [comment]
ありがとうー。よろしくお願いします。
