### ISSUE TITLE
ja.json の扱いについて

### ISSUE THREAD

**Issue by MaySoMusician** [codeforjapan/kobe-stopcovid19#10]
現在、サイトの設定としては日本語のみの設定になっています。
これから大規模な改造が行われていくとなると、言語ファイルをいちいち追従させるのは大変かと思いますが、

- Vue側の変更毎に `ja.json` を変更させていく
- ある程度目処が立ったらまとめて `ja.json` をVue側に追従させる

のどちらで行くのが良いでしょうか？

**Comment by halsk** [comment]
ある程度目処が立ったら、で良いと思います！
