### ISSUE TITLE
「最新のお知らせ」の内容差し替え

### ISSUE THREAD

**Issue by HiroSuna** [codeforjapan/kobe-stopcovid19#113]
## 起こっている問題 / The Problem
「最新のお知らせ」の内容差し替え

## 期待する見せ方・挙動 / Expected Behavior
最新のお知らせに追加するコンテンツ

1. 新型コロナウイルス感染症における神戸市の対応方針第6弾
https://www.city.kobe.lg.jp/a57337/kenko/health/corona_taiouhoshin6dan.html

2. 区役所への来庁を控えて外出の自粛にご協力ください（郵送手続・電子申請などのご案内）
https://www.city.kobe.lg.jp/a84453/20200406ann1.html

3. 5月6日（水曜・祝日）まで、学校園を臨時休業します
https://www.city.kobe.lg.jp/a57337/kenko/coc.html

**Comment by MaySoMusician** [comment]
@HiroSuna 
1. 既存のお知らせの内容は除去しますか？
1. お知らせの日付はどうしますか？

**Comment by HiroSuna** [comment]
@MaySoMusician 

> 既存のお知らせの内容は除去しますか？

全て削除してください。

> お知らせの日付はどうしますか？

①第6弾　→20200408
②区役所こないで　→20200409
③学校休み→20200408

お願いします。

**Comment by HiroSuna** [comment]
@MaySoMusician 

最新のお知らせ更新のお願いです。

1) 2020/04/22 新型コロナ対策神戸市支援総合サイトが開設しました。
https://www.city.kobe.lg.jp/a73576/kenko/health/infection/protection/corona_shien.html

2) 2020/04/22 区役所来庁を控えて下さい。
https://www.city.kobe.lg.jp/a84453/20200406ann1.html
（注意：↑日付以外変更なし）

3) 2020/4/21 医療物資に関する事業者・市民の皆さまへの提供協力のお願い
https://www.city.kobe.lg.jp/a73576/kenko/health/infection/protection/corona/corona_gaiyo.html

**Comment by MaySoMusician** [comment]
@HiroSuna 着手いたします

**Comment by MaySoMusician** [comment]
@HiroSuna 2についてですが、現在は「区役所への来庁を控えて外出の自粛にご協力ください（郵送手続・電子申請などのご案内）」になっています。「区役所来庁を控えて下さい。」に変更しますか？

**Comment by HiroSuna** [comment]
@MaySoMusician 

先方からの指示は以下の通りですが、明らかに不躾な気がするので、いったん文言はそのままで日付だけ変えてもらえますか？同時並行で、先方に確認しておきます。

「２）区役所来庁を控えて下さい。（4月22日）
そのまま」

**Comment by HiroSuna** [comment]
@MaySoMusician 
日付だけ変更という意味だったようです。確認が不十分で申し訳ありません。

**Comment by MaySoMusician** [comment]
ご確認ありがとうございます。大丈夫です
