### ISSUE TITLE
「検査陽性者の状況図」の記載項目変更とデータソース変更

### ISSUE THREAD

**Issue by HiroSuna** [codeforjapan/kobe-stopcovid19#115]
## 改善詳細 / Details of Improvement
1. 検査要請者の状況図のデータソースをexcelフォーマットに変更
2. 検査陽性者の状況図の項目変更（「検査実施人数(累計)」を「患者発生総数（速報含む）」に変更）

## スクリーンショット / Screenshot
1. のフォーマット
[yoseisyanojokyo.xlsx](https://github.com/codeforjapan/kobe-stopcovid19/files/4460088/yoseisyanojokyo.xlsx)

2. の変更箇所
![変更箇所](https://user-images.githubusercontent.com/63228590/78966810-ba78fe80-7b3b-11ea-86a1-0515490e2803.png)

## 補足 ##
1のファイルは下記サイトのどこかに配置される予定。
https://www.city.kobe.lg.jp/a73576/kenko/health/infection/protection/covid_19.html#shinaijokyo

上記ページの「神戸市内の状況」の表は、2の作業進捗に応じて神戸市側ページを変更する。良きタイミングを指示して欲しい。

**Comment by HiroSuna** [comment]
別途1のファイルを作るのではなく、下記のファイルにallのシートを追加することになりました。
![image](https://user-images.githubusercontent.com/63228590/78970248-daacbb80-7b43-11ea-8927-7449e4474f46.png)

フォーマット
[kansensya_pcr1.xlsx](https://github.com/codeforjapan/kobe-stopcovid19/files/4460283/kansensya_pcr1.xlsx)

**Comment by y-chan** [comment]
了解しました。
では、このファイルを使うようにスクリプトの変更しておきます。
新しいフォーマットのExcelが公開されるようになったうえで、私の変更後のスクリプトがこのリポジトリにマージされれば、神戸市側のサイトはいつでも変更してもらって構わないという方向でお願いします。
