### ISSUE TITLE
フローの変更・コンテンツ削除

### ISSUE THREAD

**Issue by HiroSuna** [codeforjapan/kobe-stopcovid19#1322]
## 起こっている問題 / The Problem
1. 厚労省の通知（ガイドライン変更）への対応として、フローの変更。
2. 神戸市HPと重複している以下二つのコンテンツ（ページ）の削除
-「感染症対策について」（https://kobe.stopcovid19.jp/guide）
-「神戸市電話相談窓口」（https://kobe.stopcovid19.jp/contacts）

## スクリーンショット / Screenshot
- PC版
![Screen Shot 2020-05-13 at 11 56 04](https://user-images.githubusercontent.com/63228590/81766268-c7a95480-9510-11ea-81fe-ebf8b16d46f5.png)

- スマホ
![Screen Shot 2020-05-13 at 11 57 45](https://user-images.githubusercontent.com/63228590/81766405-03dcb500-9511-11ea-83e0-26c400632754.png)

![Screen Shot 2020-05-13 at 11 57 59](https://user-images.githubusercontent.com/63228590/81766421-0b9c5980-9511-11ea-92b8-147b07b3f295.png)

**Comment by MaySoMusician** [comment]
「2. 神戸市HPと重複している以下二つのコンテンツ（ページ）の削除」についてですが、
- サイドナビゲーションのリンクは、神戸市HPへのリンクに置き換える
- https://kobe.stopcovid19.jp/guide など既に存在しているページは、削除ではなく神戸市HPへの誘導ページとする
    - https://kobe.stopcovid19.jp/guide などはサイドナビゲーションからは辿れなくなりますが、ブックマークに追加されていたり既にツイッターなどで共有されていてそこからたどり着く人もいると思います。単なる削除だとエラーページになってしまい、求めている情報がどこにあるのかわからなくなってしまうので、HPへ誘導したほうが良いのではないか、という提案です

**Comment by HiroSuna** [comment]
（提案について、神戸市担当者からの連絡待ちです）

**Comment by HiroSuna** [comment]
@MaySoMusician 
神戸市から、上記提案でお願いしますとのことです。
なお、誘導先は、以下の通りです。

-「感染症対策について」（https://kobe.stopcovid19.jp/guide）

→　https://www.city.kobe.lg.jp/a73576/kenko/health/infection/protection/coronavirus_houshin_taisaku.html

-「神戸市電話相談窓口」（https://kobe.stopcovid19.jp/contacts）

→https://www.city.kobe.lg.jp/a73576/kenko/health/infection/protection/coronavirus.html#soudansaki

**Comment by HiroSuna** [comment]
こちら、 @y-chan  さんご対応可能でしょうか？

**Comment by MaySoMusician** [comment]
@y-chan  2についてはこちらで取り掛かっているので1をお願いしたいです！

**Comment by y-chan** [comment]
少し時間かかりそうですが対応しますー

**Comment by y-chan** [comment]
解決済みのためClose
