### ISSUE TITLE
Google Analytics の設定を差し替える

### ISSUE THREAD

**Issue by halsk** [codeforjapan/kobe-stopcovid19#14]
## 改善詳細 / Details of Improvement
- Google Analytics は設定しない
- 「このサイトについて」からも削除

**Comment by HiroSuna** [comment]
神戸市よりGAの設定要望あり。

**Comment by HiroSuna** [comment]
@MaySoMusician 
こちら、ご対応いただけますでしょうか？

**Comment by MaySoMusician** [comment]
@HiroSuna 対応します！

**Comment by MaySoMusician** [comment]
@HiroSuna 「当サイトについて」に追加する文面はいかがいたしますか？

現在の東京版は以下のような感じです

---

### Google Analyticsの利用について

当サイトでは、サービス向上やサイトの改善のためにGoogle LLCの提供するアクセス分析のツールであるGoogle Analyticsを利用した計測を行っております。

Google Analyticsでは、当サイトが発行するクッキー (Cookie) 等を利用して、Webサイトの利用データ（アクセス状況、トラフィック、閲覧環境、IPアドレスなど）を収集しております。クッキーの利用に関してはGoogleのプライバシーポリシーと規約に基づいております。

取得したデータはWebサイト利用状況を分析しサービスの改善につなげるため、またはサイト運営者へのレポートを作成するため、その他のサービスの提供に関わる目的に限り、これを使用します。（サイト運営者へのレポートでは、クッキーはブラウザ単位で本サイトのユーザー数をカウントするため、IPアドレスはGoogle Analyticsの分析機能を通じてアクセス元の地域分布（国、州・都道府県、都市）を把握するために利用されています。）

Google Analyticsの利用規約及びプライバシーポリシーに関する説明については、Google Analyticsのサイトをご覧ください。

- [Google Analytics利用規約](https://marketingplatform.google.com/about/analytics/terms/jp/)
- [Googleのプライバシーポリシー](https://policies.google.com/privacy?hl=ja)
- [Google Analyticsに関する詳細情報](https://support.google.com/analytics/answer/6004245?hl=ja)

Google Analyticsによる情報送信を回避する場合は、Google がサポートする [測定を無効にするブラウザ アドオン](https://tools.google.com/dlpage/gaoptout?hl=ja) をご利用ください。

**Comment by MaySoMusician** [comment]
解析でIPアドレスを使用しないならIPアドレス匿名化というオプションもあります

**Comment by HiroSuna** [comment]
@MaySoMusician 
基本的には東京都と同様でいきましょう。
神戸市的に知りたいのはpvや離脱率、デバイス種別や流入経路くらいかと思います。
IPアドレス匿名化でも上記は分析できますか？

**Comment by MaySoMusician** [comment]
基本的に問題無いと思います。
「ユーザーがどの地域から接続しているか」で少し大雑把な分析になるぐらいのはずです。

**Comment by HiroSuna** [comment]
@MaySoMusician 
であれば、IPアドレス匿名化でいきましょう。可能な限り、個人情報に近いものは取得しない方向でお願いします。
