### ISSUE TITLE
DNS 設定を書き換える

### ISSUE THREAD

**Issue by halsk** [codeforjapan/kobe-stopcovid19#15]
## 改善詳細 / Details of Improvement
- 神戸市にお願いする

**Comment by halsk** [comment]
神戸市側のドメインではなく、こちらのドメインで運営してほしいとのこと。

https://kobe.stopcovid19.jp/ ですね。

**Comment by HiroSuna** [comment]
4/9のサイト公開の際には、神戸市は「https://kobe.stopcovid19.jp/ 」を市民に通知するということで間違い無いですか？

**Comment by halsk** [comment]
はい。DNS変更はこちらの作業なので、Issue タイトル変えました。

**Comment by y-chan** [comment]
かなり前に解決済みなのでClose
