### ISSUE TITLE
サイト閉鎖に伴う処理

### ISSUE THREAD

**Issue by HiroSuna** [codeforjapan/kobe-stopcovid19#1939]
## 起こっている問題 / The Problem
神戸市COVID-19サイト閉鎖に伴い、トップページに以下の文言を表示。

「新型コロナウイルス感染症対策サイト」は2020年6月1日より神戸市公式ホームページに統合しました。
https://www.city.kobe.lg.jp/a73576/kenko/health/infection/protection/covid_19.html

## 期待する見せ方・挙動 / Expected Behavior
移行期間終了後(1ヶ月程度？)に、GitHubのリポジトリもアーカイブ化

**Comment by HiroSuna** [comment]
@halsk 
ご対応をお願いします。

**Comment by MaySoMusician** [comment]
@HiroSuna 記述場所・デザインイメージ等の要望はありますか？

**Comment by HiroSuna** [comment]
@MaySoMusician 
特にありません。短期間での作業なので、こちらに任せてもらうことで合意が取れています。
