### ISSUE TITLE
サイドメニューを修正する

### ISSUE THREAD

**Issue by halsk** [codeforjapan/kobe-stopcovid19#2]
## 改善詳細 / Details of Improvement
- サイドメニューを仕様書通りに変更

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by MaySoMusician** [comment]
こちらやりますー
