### ISSUE TITLE
神戸市要確認リスト

### ISSUE THREAD

**Issue by MaySoMusician** [codeforjapan/kobe-stopcovid19#20]
- [x] 公式SNSアカウント等のリンク先を確認する
- LINE
- Twitter
- Facebook
---

- GitHub
  - 確認待ち

**Comment by MaySoMusician** [comment]
- 「帰国者・接触者相談センター電話番号」は24時間対応なのか。日中は東京都と同様に保健所へ誘導するのか
  - 参考: 「神戸市新型コロナウイルス感染症帰国者・接触者相談センター」についての発表
https://www.city.kobe.lg.jp/a73576/kenko/health/infection/protection/coronavirus_kisha2.html

**Comment by halsk** [comment]
* エクセルに退院列がない

**Comment by MaySoMusician** [comment]
- aboutページのオープンカタログサイト・GitHub レポジトリの記述をどうするか

**Comment by MaySoMusician** [comment]
- [x] 「神戸市電話相談窓口」の内容

**Comment by y-chan** [comment]
陽性患者の属性のエクセルデータを追加してもらう(退院列はこちらに追加)
西宮市在住者の扱いがよくわからないので、陽性患者の属性表の人数と、検査陽性者の状況図とで陽性患者の人数が合っていないのをどうすればよいか確認

**Comment by halsk** [comment]
まとめて回答をもらったので貼っておきます
[頂いたご質問について.docx](https://github.com/codeforjapan/kobe-stopcovid19/files/4403603/default.docx)
