### ISSUE TITLE
「検査陽性者の状況」のテキスト変更

### ISSUE THREAD

**Issue by HiroSuna** [codeforjapan/kobe-stopcovid19#282]
## 改善詳細 / Details of Improvement
「検査陽性者の状況」のテキストを変更。
１．入院中を「入院中等」に変更。
２．注意書きに加えていただくことと。
⇒「入院中等」は、入院調整中・宿泊療養に移行した人を含みます。

## スクリーンショット / Screenshot
![Screen Shot 2020-04-17 at 11 51 37](https://user-images.githubusercontent.com/63228590/79527254-11358980-80a2-11ea-9155-1612768b85cc.png)

**Comment by y-chan** [comment]
対応します。
