### ISSUE TITLE
訂正依頼 0331

### ISSUE THREAD

**Issue by halsk** [codeforjapan/kobe-stopcovid19#34]
添付の内容に修正
[訂正依頼 (1).pdf](https://github.com/codeforjapan/kobe-stopcovid19/files/4409179/1.pdf)

関連データ
[20200331_9時相談件数 (1).xlsx](https://github.com/codeforjapan/kobe-stopcovid19/files/4409176/20200331_9.1.xlsx)
[属性一覧参考 (1).xlsx](https://github.com/codeforjapan/kobe-stopcovid19/files/4409177/1.xlsx)

なにか不明点があれば聞いてください

**Comment by y-chan** [comment]
グラフ関連の訂正に関して、修正に当たります。

**Comment by MaySoMusician** [comment]
とりあえず①②の変更やります

**Comment by y-chan** [comment]
@MaySoMusician ①の変更に合わせて、サイドナビゲーションの「市内の最新感染動向」も「神戸市」にすべきかと思いました。
お気づきでしたら申し訳ないですが、こちらも表現統一ということでお願いしておきます。

**Comment by MaySoMusician** [comment]
> グラフ関連の訂正に関して、修正に当たります。

丸数字で言うとどの部分を修正していますか？

**Comment by y-chan** [comment]
データ自体の修正(⑥、⑧)をしています。
⑩、⑪も伴ってくると思うので、それ以外のタイトルや注記の修正をお願いできますでしょうか？

**Comment by MaySoMusician** [comment]
@halsk 訂正依頼のPDFの③と⑤についてですが、
> ③ 注）「治癒確認（退院など）」とは検査で（略）
> ⑤ 治癒確認（退院等）

というように「など」の部分で表記ゆれがあります。どちらかに統一したほうが良いでしょうか？

**Comment by y-chan** [comment]
@MaySoMusician 
ごめんなさい、先ほど⑥、⑧、⑩、⑪と言いましたが、グラフ自体の変更や、データの形式の変更で⑦、⑨もいじっています。
コンフリクトを避けるためにそれ以外をお願いします、何度も申し訳ないです。

**Comment by y-chan** [comment]
データの作り直し等行っているのですが、Webスクレイピングで取得したデータは新しくなるのですが、現状頂いたxlsxデータから生成したものに関しては古いままで、数値が合いません...
一旦このままPRに回しても大丈夫でしょうか...?
![image](https://user-images.githubusercontent.com/34832037/78053519-ad317680-73bb-11ea-89ca-40b72f20c4ea.png)

**Comment by MaySoMusician** [comment]
たぶん本issueの作業は終わっているはずです。ダブルチェックお願いします

**Comment by MaySoMusician** [comment]
と思ったんですがSNSアカウントの差し替えがまだでした

**Comment by halsk** [comment]
確認しました。ありがとうございます！
