### ISSUE TITLE
flowページの「帰国者・接触者 電話相談センター」周りのデザイン修正

### ISSUE THREAD

**Issue by MaySoMusician** [codeforjapan/kobe-stopcovid19#39]
## 改善詳細 / Details of Improvement
- #38 で電話番号などを変更したが、日中・夜間で別々に記載していたのを24時間対応として統一した影響で、図に空きスペースが生まれてしまっている

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/34566290/78045703-3becc600-73b1-11ea-91e4-77182a9900ae.png)

**Comment by ishayashi** [comment]
薄いグレーの囲いを付けましょう！

`border: 3px solid #4d4d4d;`

[![Screenshot from Gyazo](https://infosign-inc.gyazo.com/f2349c70cfc29df8a79a0840233b5456/raw)](https://infosign-inc.gyazo.com/f2349c70cfc29df8a79a0840233b5456)

**Comment by forestgtree** [comment]
薄いグレー部分にボーダーを付けましょう。

`border: 3px solid #4d4d4d;`

[![Screenshot from Gyazo](https://infosign-inc.gyazo.com/f2349c70cfc29df8a79a0840233b5456/raw)](https://infosign-inc.gyazo.com/f2349c70cfc29df8a79a0840233b5456)
