### ISSUE TITLE
サイトの文言変更

### ISSUE THREAD

**Issue by HiroSuna** [codeforjapan/kobe-stopcovid19#448]
## 改善詳細 / Details of Improvement
検査陽性者の状況図のテキストを下記のように変更
before）「入院中等」は、入院調整中・宿泊療養に移行した人を含みます。
after)「入院・入居中」は、宿泊療養に移行した人を含みます。

before) 入院中等
after) 入院・入居中

## スクリーンショット / Screenshot
![Screen Shot 2020-04-24 at 16 16 59](https://user-images.githubusercontent.com/63228590/80185285-1157fb00-8647-11ea-8979-c2a2beb2445f.png)

**Comment by HiroSuna** [comment]
確認漏れていました、図中の文言を訂正願います。

before) 入院・入院中
after) 入院・入居中

**Comment by HiroSuna** [comment]
@y-chan 
ご確認を〜

**Comment by y-chan** [comment]
すみません、確認しました。
訂正に当たります。
