### ISSUE TITLE
スマホ画面で「市内でのPCR検査件数」が表示されていない

### ISSUE THREAD

**Issue by HiroSuna** [codeforjapan/kobe-stopcovid19#584]
## 起こっている問題 / The Problem
スマホ画面で「市内でのPCR検査件数」が表示されていない

## スクリーンショット / Screenshot
![IMG_1488](https://user-images.githubusercontent.com/63228590/80354473-c1c93780-88b1-11ea-9881-8cb562c4a01e.PNG)

## 期待する見せ方・挙動 / Expected Behavior
「市内でのPCR検査件数」がスマホで表示される

## 動作環境・ブラウザ / Environment
-  iOS
- Chrome / Safari

**Comment by y-chan** [comment]
PCでも消えちゃってますね
![image](https://user-images.githubusercontent.com/34832037/80354868-46b45100-88b2-11ea-9e13-cad6b9f66f84.png)

**Comment by y-chan** [comment]
コンソールログを見てみると、データ自体に問題がありそう...??
![image](https://user-images.githubusercontent.com/34832037/80354989-6fd4e180-88b2-11ea-810c-9795e720cb08.png)

**Comment by y-chan** [comment]
スクリプトに問題があるようで、nullが代入されていておかしくなっていたのですね....
今までの運用では問題なかったはずなので、ちょっと何が問題なのか見てみます。
https://github.com/codeforjapan/kobe-stopcovid19/commit/5d91ea192438f05d7c53a65814be88ae7e6e9176#diff-868ae2d65fb52e0bf680b28558a92a88R1759

**Comment by y-chan** [comment]
調査した結果、神戸市が公開するファイルの問題でした。
![image](https://user-images.githubusercontent.com/34832037/80355661-53857480-88b3-11ea-8944-d6d79adb6e1d.png)
https://www.city.kobe.lg.jp/documents/32576/kansensya_pcr.xlsx
~~上記のファイルで、4/27の検査実施人数の欄が空になってしまっていたためで、人為的ミスによるものだと思います。
データ整形スクリプトに問題があるわけではありませんでした。~~
今後これをどう例外処理させるかの検討が必要ですね

**Comment by HiroSuna** [comment]
@y-chan 
了解です。神戸市側には「空白ではなく、何か数字を入れてくれ」と伝えればOKですか？または、空白の場合は、とりあえず機械的に0を代入しておく、とでも伝えましょうか？

**Comment by y-chan** [comment]
そうですね、最低でも0の代入をお願いしてほしいです。
