### ISSUE TITLE
リンク切れ・リンク先変更

### ISSUE THREAD

**Issue by HiroSuna** [codeforjapan/kobe-stopcovid19#59]
## 起こっている問題 / The Problem
リンク切れ・リンク先変更の対応

## スクリーンショット / Screenshot

[修正内容.docx](https://github.com/codeforjapan/kobe-stopcovid19/files/4447561/default.docx)

## 期待する見せ方・挙動 / Expected Behavior
4/9のサイト公開までに対応が必要

**Comment by y-chan** [comment]
こちらの修正、対応します
