### ISSUE TITLE
サイトの文言変更

### ISSUE THREAD

**Issue by HiroSuna** [codeforjapan/kobe-stopcovid19#623]
## 改善詳細 / Details of Improvement
フローの「新型コロナ受診相談窓口」を「新型コロナ専用健康相談窓口」に変更

## スクリーンショット / Screenshot
![Screen Shot 2020-04-28 at 13 58 49](https://user-images.githubusercontent.com/63228590/80448810-6e5df480-8958-11ea-9755-0cc5ea8ff331.png)

**Comment by HiroSuna** [comment]
@y-chan 
お願いできますか？？

**Comment by y-chan** [comment]
了解しました
