### ISSUE TITLE
サイトに表示される内容の修正

### ISSUE THREAD

**Issue by HiroSuna** [codeforjapan/kobe-stopcovid19#69]
## 起こっている問題 / The Problem
サイトに表示されている内容の修正。データとは関係ない箇所。

## スクリーンショット / Screenshot
[修正依頼（最後）.pdf](https://github.com/codeforjapan/kobe-stopcovid19/files/4449113/default.pdf)

**Comment by MaySoMusician** [comment]
ひとまず修正箇所1・2をやります

**Comment by MaySoMusician** [comment]
修正箇所1: #71 
修正箇所2: #72

**Comment by MaySoMusician** [comment]
修正箇所3: #73

**Comment by MaySoMusician** [comment]
Close per #71 #72 #73 merged
