### ISSUE TITLE
二つに分かれたグラフの統合（オープンデータ側の数値も統合される予定）

### ISSUE THREAD

**Issue by HiroSuna** [codeforjapan/kobe-stopcovid19#70]
## 起こっている問題 / The Problem
二種類のグラフ①新型コロナ健康健康窓口と②帰国者・接触者相談センターの相談件数）の統合して、一つのグラフにする。（元のデータ自体を合算する）

背景）新型コロナ健康相談窓口と帰国者・接触者相談センターの統合されることになった。
参照するオープンデータの方も、担当者がすぐに変更できると連絡あり。

**Comment by HiroSuna** [comment]
変更後のグラフのタイトルは「健康相談窓口(帰国者・接触者相談センター）」で、オープンデータのフォーマットは以下の通りだそうです。

[sodan2 (1).xlsx](https://github.com/codeforjapan/kobe-stopcovid19/files/4449431/sodan2.1.xlsx)

**Comment by y-chan** [comment]
確認しました、ありがとうございます。
修正します。
