### ISSUE TITLE
auto merge bot の導入

### ISSUE THREAD

**Issue by halsk** [codeforjapan/kobe-stopcovid19#77]
## 改善詳細 / Details of Improvement
- auto merge bot を導入する

**Comment by HiroSuna** [comment]
市側の運用も安定してきたので、本番環境にもオートマージbot導入しましょう。
@y-chan さんですかね？

**Comment by y-chan** [comment]
大丈夫だと思います。
私に権限は無いので、@halsk さんにお願いします。

**Comment by y-chan** [comment]
ごめんなさい、いろいろ勘違いしてました...
botの導入は終わっているので、GitHub Actionsの方の設定になりますね。
失礼しました。

**Comment by MaySoMusician** [comment]
導入完了してるようなので一度Close
