### ISSUE TITLE
Facebook App ID を正式なものに差し替える

### ISSUE THREAD

**Issue by MaySoMusician** [codeforjapan/kobe-stopcovid19#87]
- #86 で東京版ではないものにはなっている
- 神戸市のFacebook管理と合わせる必要がある

**Comment by HiroSuna** [comment]
https://www.facebook.com/kobekoho/
上記ページのFB App ID(278274305582570)を提案しようと思っていますが、先方から「そもそもなぜ必要なのか」を聞かれています。どなたかコメントいただけると幸いです。

**Comment by MaySoMusician** [comment]
一部ネットの解説でも情報が錯綜しているのですが、一般的には「Facebook向けOGPの設定に必要なApp ID」と位置付けられています

**Comment by MaySoMusician** [comment]
@HiroSuna こちらですがどうしましょう？ 特に問題なければ `278274305582570` に変更してしまおうと思います

**Comment by y-chan** [comment]
必要が無くなったためClose
